src/Entity/Medicament.php
<?php

namespace App\Entity;

use App\Repository\MedicamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedicamentRepository::class)
 */
class Medicament
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_peremp;

    /**
     * @ORM\Column(type="text")
     */
    private $cible;
    
        /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $mode_conso;

       /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit_boite;

       /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit_carton;

       /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit_plaquette;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $stock;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $effet_secondaire;

    /**
     * @ORM\ManyToMany(targetEntity=Transaction::class, mappedBy="id_medicament")
     */
    private $transactions;

    /**
     * @ORM\OneToMany(targetEntity=TransactionLine::class, mappedBy="id_medicament")
     */
    private $transactionLines;

    /**
     * @ORM\OneToOne(targetEntity=Stock::class, mappedBy="medicament", cascade={"persist", "remove"})
     */
    private $the_stock;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
        $this->transactionLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatePeremp(): ?\DateTimeInterface
    {
        return $this->date_peremp;
    }

    public function setDatePeremp(\DateTimeInterface $date_peremp): self
    {
        $this->date_peremp = $date_peremp;

        return $this;
    }

    public function getCible(): ?string
    {
        return $this->cible;
    }

    public function setCible(string $cible): self
    {
        $this->cible = $cible;

        return $this;
    }
    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getModeConso(): ?string
    {
        return $this->mode_conso;
    }

    public function setModeConso(string $mode_conso): self
    {
        $this->mode_conso = $mode_conso;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getEffetSecondaire(): ?string
    {
        return $this->effet_secondaire;
    }

    public function setEffetSecondaire(?string $effet_secondaire): self
    {
        $this->effet_secondaire = $effet_secondaire;

        return $this;
    }

    public function getPriceUnitCarton(): ?string
    {
        return $this->price_unit_carton;
    }

    public function setPriceUnitCarton(string $price_unit_carton): self
    {
        $this->price_unit_carton = $price_unit_carton;

        return $this;
    }

    public function getPriceUnitBoite(): ?string
    {
        return $this->price_unit_boite;
    }

    public function setPriceUnitBoite(string $price_unit_boite): self
    {
        $this->price_unit_boite= $price_unit_boite;

        return $this;
    }

    public function getPriceUnitPlaquette(): ?string
    {
        return $this->price_unit_plaquette;
    }

    public function setPriceUnitPlaquette(string $price_unit_plaquette): self
    {
        $this->price_unit_plaquette = $price_unit_plaquette;

        return $this;
    }

    /**
     * @return Collection<int, Transaction>
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->addIdMedicament($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->removeElement($transaction)) {
            $transaction->removeIdMedicament($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, TransactionLine>
     */
    public function getTransactionLines(): Collection
    {
        return $this->transactionLines;
    }

    public function addTransactionLine(TransactionLine $transactionLine): self
    {
        if (!$this->transactionLines->contains($transactionLine)) {
            $this->transactionLines[] = $transactionLine;
            $transactionLine->setIdMedicament($this);
        }

        return $this;
    }

    public function removeTransactionLine(TransactionLine $transactionLine): self
    {
        if ($this->transactionLines->removeElement($transactionLine)) {
            // set the owning side to null (unless already changed)
            if ($transactionLine->getIdMedicament() === $this) {
                $transactionLine->setIdMedicament(null);
            }
        }

        return $this;
    }

    public function getTheStock(): ?Stock
    {
        return $this->the_stock;
    }

    public function setTheStock(?Stock $the_stock): self
    {
        // unset the owning side of the relation if necessary
        if ($the_stock === null && $this->the_stock !== null) {
            $this->the_stock->setMedicament(null);
        }

        // set the owning side of the relation if necessary
        if ($the_stock !== null && $the_stock->getMedicament() !== $this) {
            $the_stock->setMedicament($this);
        }

        $this->the_stock = $the_stock;

        return $this;
    }
}

src/Form/MedicamentType.php
<?php

namespace App\Form;

use App\Entity\Medicament;
use App\Entity\TheNewStock;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\StockType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class MedicamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('mode_conso')
            // ->add('date_peremp')
            ->add('cible')
            ->add('note')
            ->add('stock')
            ->add('effet_secondaire')
            ->add('date_peremp',DateType::class)
        
            // ->add('transaction_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Medicament::class,
        ]);
    }

    
}

src/Controller/MedicamentController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MedicamentRepository;
use App\Repository\StockRepository;
use App\Entity\BlocNote;
use App\Entity\Stock;
use App\Entity\Medicament;
use App\Form\MedicamentType;

class MedicamentController extends AbstractController
{
    /**
     * @Route("/medicament", name="app_medicament")
     */
    public function index(MedicamentRepository $medicamentRepository,Request $request): Response
    {
      $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
      $hasAccess = $this->isGranted('ROLE_ADMIN');
      $this->denyAccessUnlessGranted('ROLE_ADMIN');

      $term='';
      if ( $request->query->has('input_search')) {
        $term = $request->query->get('input_search');

        if (!empty($term)) {
          $result=$medicamentRepository->search_medicament($term);
   

      return $this->render('medicament/index.html.twig', [
        'medicament' => $result,
        'term' => $term
    ]);
    }
  }
      
      $all_medicament=$medicamentRepository->findAll();
        return $this->render('medicament/index.html.twig', [
            'medicament' => $all_medicament,
            'term' => $term,
        ]);
    }

     /**
     * @Route("/medicament/create", name="app_medicament_create")
     */
    public function create(Request $request,StockRepository $stockRepository): Response
    { 
      $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
      $hasAccess = $this->isGranted('ROLE_ADMIN');
      $this->denyAccessUnlessGranted('ROLE_ADMIN');

      $date=new \DateTime();
      $newDate = $date->format('Y-m-d');
      // dd($newDate);
        //  $the_date=date('Y-m-d H:i:s',$date);
      // $date_peremp=new \DateTime($the_date);
        $medicament=new Medicament();
        // $new=new \DateTime(ow);
        //$all_medicament=$medicamentRepository->findAll();
        $form = $this->createForm(MedicamentType::class, $medicament);
        $stock=$stockRepository->findAll();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($medicament);
            $entityManager->flush();

            return $this->redirectToRoute('app_medicament');
        }
        return $this->render('medicament/create.html.twig', [
            'medicament' => $medicament,
            'stock' => $stock,
            'date' => $newDate,
            'form' => $form->createView(),
        ]);

    }

      /**
     * @Route("/medicament/store", name="app_medicament_store")
     */
    public function store(Request $request,MedicamentRepository $productRepository ,StockRepository $stockRepository)
    { 
        try{

            $date_tr=$request->get('date_peremp');
 
        $the_date=date('Y-m-d H:i:s',strtotime($date_tr));
        $date_peremp=new \DateTime($the_date);

        $name=$request->get('name');
        $cible=$request->get('cible');
        $mode_conso=$request->get('mode_conso');
        $effet_secondaire=$request->get('effet_secondaire');
        $note=$request->get('note');
        $price_unit_carton=$request->get('price_unit_carton');
        $price_unit_boite=$request->get('price_unit_boite');
        $price_unit_plaquette=$request->get('price_unit_plaquette');
        $entityManager=$this->getDoctrine()->getManager();

        if (empty($name || $cible || $price_unit_carton||$price_unit_boite || $price_unit_plaquette)){
            return $this->redirectToRoute('app_medicament_create');
            }

        $medicament=new Medicament;
        
        $medicament->setName($name);
        $medicament->setCible($cible);
        $medicament->setModeConso($mode_conso);
        $medicament->setEffetSecondaire($effet_secondaire);
        $medicament->setNote($note);
        $medicament->setDatePeremp($date_peremp);
        $medicament->setPriceUnitPlaquette($price_unit_plaquette);
        $medicament->setPriceUnitCarton($price_unit_carton);
        $medicament->setPriceUnitBoite($price_unit_boite);

        $entityManager->persist($medicament);
        
        //  $entityManager->flush();

         $carton=$request->get('carton');
         $boite=$request->get('boite');
         $plaquette=$request->get('plaquette');

         if (empty($carton )){
            $carton=0;
            }
          if (empty($boite )){
            $boite=0;
            }
         if (empty($plaquette )){
            $plaquette=0;
            }

          $stock=new Stock;

          $stock->setCarton($carton);
          $stock->setBoite($boite);
          $stock->setplaquette($plaquette);
          $stock->setMedicament($medicament);
          $entityManager->persist($stock);
          $entityManager->flush();

          $output = ['success' => 1,
                            'msg' =>('medicament added successfully')
        ];
        return $this->redirectToRoute('app_medicament');
          } catch (\Exception $e) {
            // DB::rollBack();
            // \Log::emergency("File:" . $e->getFile(). "Line:" . $e->getLine(). "Message:" . $e->getMessage());
            
            $output = ['success' => 0,
                            'msg' =>("something went wrong")
                        ];
                        return $this->redirectToRoute('app_medicament_create');
            
        }

    }

     /**
     * @Route("/medicament/{id}", name="app_medicament_show", methods={"GET"})
     */

    public function show(Medicament $medicament,$id,MedicamentRepository $medicamentRepository): Response
    {  
      $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
      $hasAccess = $this->isGranted('ROLE_ADMIN');
      $this->denyAccessUnlessGranted('ROLE_ADMIN');
      
      $the_medicament=$medicamentRepository->find($id);
        return $this->render('medicament/show.html.twig', [
            'medicament' => $the_medicament,
        ]);
    }

    
     /**
     * @Route("/medicament/{id}/edit", name="app_medicament_edit", methods={"GET","POST"})
     */
    public function edit(Request $request,MedicamentRepository $productRepository ,$id,StockRepository $stockRepository): Response
       {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $hasAccess = $this->isGranted('ROLE_ADMIN');
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

     $product=$productRepository->find($id);
   
     $all_product=$productRepository->findAll();
     return $this->render('medicament/edit.html.twig', [
        'medicament' => $product,
        'all_medicament' => $all_product
        ]);
    }


       /**
     * @Route("/medicament/update/id={id}", name="app_medicament_update")
     */
    public function update(Request $request,$id,MedicamentRepository $productRepository,StockRepository $stockRepository )
    { 
      $entityManager=$this->getDoctrine()->getManager();
      $medicament=$entityManager->getRepository(Medicament::class)->find($id);

    $route = $request->headers->get('referer');
      $date_tr=$request->get('date_peremp');
      $the_date=date('Y-m-d H:i:s',strtotime($date_tr));
      $date_peremp=new \DateTime($the_date);

      $name=$request->get('name');
      $cible=$request->get('cible');
      $mode_conso=$request->get('mode_conso');
      $effet_secondaire=$request->get('effet_secondaire');
      $note=$request->get('note');
      $price_unit_carton=$request->get('price_unit_carton');
      $price_unit_boite=$request->get('price_unit_boite');
      $price_unit_plaquette=$request->get('price_unit_plaquette');
      $entityManager=$this->getDoctrine()->getManager();

      if (empty($name || $cible || $price_unit_carton||$price_unit_boite || $price_unit_plaquette)){
        return $this->redirect($route);
          }

      $medicament->setName($name);
      $medicament->setCible($cible);
      $medicament->setModeConso($mode_conso);
      $medicament->setEffetSecondaire($effet_secondaire);
      $medicament->setNote($note);
      $medicament->setDatePeremp($date_peremp);
      $medicament->setPriceUnitPlaquette($price_unit_plaquette);
      $medicament->setPriceUnitCarton($price_unit_carton);
      $medicament->setPriceUnitBoite($price_unit_boite);

      $entityManager->persist($medicament);
      
      //  $entityManager->flush();
       $carton=$request->get('carton');
       $boite=$request->get('boite');
       $plaquette=$request->get('plaquette');
      
       if (empty($carton )){
        $carton=0;
        }
      if (empty($boite )){
        $boite=0;
        }
     if (empty($plaquette )){
        $plaquette=0;
        }
        $medicament=$entityManager->getRepository(Medicament::class)->find($id);
        $med=$medicament->getTheStock()->getId();
        $qb = $stockRepository->createQueryBuilder('stock');
       
        $qb->where("stock.id ='$med'");
        $stock=$qb->getQuery()->getResult();
        $stock[0]->setCarton($carton);
        $stock[0]->setBoite($boite);
        $stock[0]->setplaquette($plaquette);
        $stock[0]->setMedicament($medicament);
        $entityManager->persist($stock[0]);
        $entityManager->flush();

      return $this->redirectToRoute('app_medicament');
    }

      /**
     * @Route("/medicament/delete/{id}", name="app_medicament_delete")
     */
    public function delete(Request $request, Medicament $medicament,StockRepository $stockRepository ): Response
    {
      $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
      $hasAccess = $this->isGranted('ROLE_ADMIN');
      $this->denyAccessUnlessGranted('ROLE_ADMIN');
      
            $entityManager = $this->getDoctrine()->getManager();
            
          if(!empty($medicament->getTheStock())){
            $med=$medicament->getTheStock()->getId();

templates/medicament/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add medicament{% endblock %}

{% block body %}
  <div class="col-md-12">
<H1>
Add medicament
</H1>


 <form  class="form-control form_medicament" method="POST" action="{{path('app_medicament_store')}}"> 
<div class="container">
<div class="row">
<div class="form-group col-md-3">
 <label for="name">Name:</label>
    <input type="text" name="name" class="form-control" id="name" required placeholder="name">
</div>
<div class="form-group col-md-6">
 <label for="cible">cible:</label>
    <textarea name="cible" id="cible" class="form-control" required placeholder="cible" ></textarea>
</div>
<div class="form-group col-md-3">
 <label for="date_peremp">date peremption:</label>
    <input type="text" class="js-datetimePicker" name="date_peremp" required value="{{date}}" id="date_peremp" class="form-control" />
</div>
</div>
<div class="row">

<div class="form-group col-md-6">
 <label for="mode_conso">mode consommation:</label>
    <textarea name="mode_conso" id="mode_conso" class="form-control" required placeholder="mode de consommation" ></textarea>
</div>
<div class="form-group col-md-6">
 <label for="effet_secondaire">effet secondaire:</label>
    <textarea name="effet_secondaire" id="effet_secondaire" class="form-control" placeholder="effet secondaire" ></textarea>
</div>
</div>
<div class="form-group">
 <label for="note">Note:</label>
    <textarea name="note" id="note" class="form-control" placeholder="note" ></textarea>
</div>
<hr>
<H2>Stock</h2>
<div class="row">
<div class="form-group col-md-4">
 <label for="carton">Carton:</label>
    <input type="number" name="carton" class="form-control"  id="carton">
</div>
<div class="form-group col-md-4">
 <label for="boite">Boite:</label>
    <input type="number" name="boite" class="form-control" id="boite">
</div>
<div class="form-group col-md-4">
 <label for="plaquette">Plaquette:</label>
    <input type="number" name="plaquette" class="form-control" id="plaquette">
</div>
</div>

<hr>
<H2>Price</h2>
<div class="row">
<div class="form-group col-md-4">
 <label for="price_unit_carton">Prix par carton:</label>
    <input type="number" name="price_unit_carton" class="form-control" required id="price_unit_carton">
</div>
<div class="form-group col-md-4">
 <label for="price_unit_boite">Prix par boite:</label>
    <input type="number" name="price_unit_boite" class="form-control" required id="price_unit_boite">
</div>
<div class="form-group col-md-4">
 <label for="price_unit_plaquette">Prix par plaquette:</label>
    <input type="number" name="price_unit_plaquette" class="form-control" required id="price_unit_plaquette">
</div>
</div>
<br>

 <div class="d-flex  justify-content-end">
   <button type="submit" class="btn btn-success pull-right">Add</button>
   </div>
</div>
    </form>   

    {% endblock %}

templates/medicament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit medicament{% endblock %}

{% block body %}
 <div class="col-md-12">
<H1>
Edit medicament
</H1>


 <form  class="form-control" method="POST" action="{{path('app_medicament_update', {'id': medicament.id} )}}"> 
<div class="container">
<div class="row">
<div class="form-group col-md-3">
 <label for="name">Name:</label>
    <input type="text" name="name" class="form-control" id="name" value="{{medicament.name}}" placeholder="name">
</div>
<div class="form-group col-md-6">
 <label for="cible">cible:</label>
    <textarea name="cible" id="cible" class="form-control"  placeholder="cible" >{{medicament.cible}}</textarea>
</div>
<div class="form-group col-md-3">
 <label for="date_peremp">date peremption:</label>
    <input type="text" class="js-datetimePicker" name="date_peremp" id="date_peremp" value="{{medicament.datePeremp|date('Y-m-d') }}"  class="form-control" />
</div>
</div>
<div class="row">

<div class="form-group col-md-6">
 <label for="mode_conso">mode consommation:</label>
    <textarea name="mode_conso" id="mode_conso" class="form-control" placeholder="mode de consommation" >{{medicament.modeConso}}</textarea>
</div>
<div class="form-group col-md-6">
 <label for="effet_secondaire">effet secondaire:</label>
    <textarea name="effet_secondaire" id="effet_secondaire" class="form-control"  placeholder="effet secondaire" >{{medicament.effetSecondaire}}</textarea>
</div>
</div>
<div class="form-group">
 <label for="note">Note:</label>
    <textarea name="note" id="note" class="form-control"  placeholder="note" >{{medicament.note}}</textarea>
</div>
<hr>
<H2>Stock</h2>
<div class="row">
<div class="form-group col-md-4">
 <label for="carton">Carton:</label>
    <input type="number" name="carton" class="form-control" id="carton" value="{{medicament.theStock.carton}}">
</div>
<div class="form-group col-md-4">
 <label for="boite">Boite:</label>
    <input type="number" name="boite" class="form-control" id="boite" value="{{medicament.theStock.boite}}">
</div>
<div class="form-group col-md-4">
 <label for="plaquette">Plaquette:</label>
    <input type="number" name="plaquette" class="form-control" id="plaquette" value="{{medicament.theStock.plaquette}}">
</div>
</div>

<hr>
<H2>Price</h2>
<div class="row">
<div class="form-group col-md-4">
 <label for="price_unit_carton">Prix par carton:</label>
    <input type="number" name="price_unit_carton" class="form-control" id="price_unit_carton" value="{{medicament.priceUnitCarton}}">
</div>
<div class="form-group col-md-4">
 <label for="price_unit_boite">Prix par boite:</label>
    <input type="number" name="price_unit_boite" class="form-control" id="price_unit_boite" value="{{medicament.priceUnitBoite}}">
</div>
<div class="form-group col-md-4">
 <label for="price_unit_plaquette">Prix par plaquette:</label>
    <input type="number" name="price_unit_plaquette" class="form-control" id="price_unit_plaquette" value="{{medicament.priceUnitPlaquette}}">
</div>
</div>
<br>

 <div class="d-flex  justify-content-end">
   <button type="submit" class="btn btn-success pull-right">Update</button>
   </div>
</div>
    </form>   

</div>
    {% endblock %}

templates/medicament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}medicament{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div class="example-wrapper">

<div class="d-flex">
<div class="col-sm-6">
    <h1>All medicaments</h1>
    </div>
<div class="col-sm-6 "> 
        
      <a href="{{path('app_medicament_create')}}"  class="btn btn-primary float-end"><i class="fa fa-plus" aria-hidden="true"></i>Add</a>
      
      </div>
    </div>
</div>
<div class="row">
<div class="col-md-12">
<input class="form-control float-end" id="search_med" type="search" value="{{term}}" placeholder="Search" aria-label="Search" style="width:150px;">

</div>
</div>

<div class="table-responsive"> 
<table class="table table-bordered">
<thead>
<tr>

<th>name</th>
<th>cible</th>
<th>mode emploi</th>
<th>effet secondaire</th>
<th>date de peremption</th>

<th>note</th>

</tr>
</thead>
{% if medicament|length > 0 %}
{%for medicaments in medicament %}
 {# {{dd(sell)}} #}
<tbody>
<tr>
<td>{{medicaments.name}}</td>
<td>{{medicaments.cible }}</td>
<td>{{medicaments.modeConso }}</td>
<td>{{medicaments.effetSecondaire }}</td>
<td>{{medicaments.datePeremp|date('d-m-Y')  }}</td>

<td>{{medicaments.note }}</td>

<td>
<div class="btn-group" role="group">
<button type="button" id="btnGroupDrop1"  class="btn btn-primary dropdown-toggle" aria-haspopup="true" aria-expanded="false" data-bs-toggle="dropdown">Action <span class="caret"></span></button>
<div class="dropdown-menu" >
<button type="button" href="" data-bs-toggle="modal" data-href="{{path('app_medicament_show', {id: medicaments.id})}}"  data-bs-target="#create_modal"  class="dropdown-item my_modal" ><i class="fas fa-eye" aria-hidden="true"></i> view</button>

<a href="{{path('app_medicament_edit', {id: medicaments.id})}}"  class="dropdown-item" ><i class="fas fa-edit" aria-hidden="true"></i>edit</a>

<a href="{{path('app_medicament_delete', {id: medicaments.id})}}"  class="dropdown-item"><i class="fas fa-trash" aria-hidden="true"></i>delete</a>
</div>
</div>
</td>


</tr>
</tbody>
 {% endfor %}

{% else %}
<tbody>
<tr>
<td colspan="6">
 <H4 class="text-center">vide</H4>
 </td>
 </tr>
 </tbody>
 {% endif %}

</table>
</div>
{# </div> #}
   <div class="modal fade modal" id="create_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
         
       </div>  
       </div>
{% endblock %}

templates/medicament/show.html.twig
<div class="modal-content">
       
            <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Medicament</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

            </div>
            <div class="modal-body">

            <div class="row">
<div class="col-md-4">
<b>Name:</b>
{{medicament.name}}
<br>
<b>Cible:</b><br>
{% if medicament.cible is not empty %}
   {{medicament.cible}}
<br>     
{% endif %}

<b>Mode d'emploi:</b><br>
{% if medicament.modeConso is not empty %}
{{medicament.modeConso}}
<br>
{% endif %}
<b>Effet secondaire:</b><br>
{% if medicament.effetSecondaire is not empty %}
{{medicament.effetSecondaire}}
<br>
{% endif %}
<b>Date peremption:</b>
{% if medicament.datePeremp is not empty %}
<br>
{{medicament.datePeremp|date('d-m-Y') }}
{% endif %}
{# <b>Mode d'emploi:</b><br>
{{medicament.effet_secondaire}} #}
</div>


<div class="col-md-4">
<b>Prix par carton:</b>
{{medicament.priceUnitCarton}}
<br>
<b>Prix par boite:</b>
{{medicament.priceUnitBoite}}
<br>
<b>Prix par plaquette:</b>
{{medicament.priceUnitPlaquette}}

</div>


<div class="col-md-4">
<b>Stock en carton:</b>
{{medicament.theStock.carton}}
<br>
<b>Stock en boite:</b>
{{medicament.theStock.boite}}
<br>
<b>Stock en plaquette:</b>
{{medicament.theStock.plaquette}}

</div>
</div>
<br>

<div class="note">
<b>Note:</b><br>
{{medicament.note}}
</div>
<br>
 <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
 </div>
</div>