src/Entity/Medicament.php
<?php

namespace App\Entity;

use App\Repository\MedicamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedicamentRepository::class)
 */
class Medicament
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_peremp;

    /**
     * @ORM\Column(type="text")
     */
    private $cible;
    
        /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $mode_conso;

       /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit_boite;

       /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit_carton;

       /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_unit_plaquette;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $stock;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $effet_secondaire;

    /**
     * @ORM\ManyToMany(targetEntity=Transaction::class, mappedBy="id_medicament")
     */
    private $transactions;

    /**
     * @ORM\OneToMany(targetEntity=TransactionLine::class, mappedBy="id_medicament")
     */
    private $transactionLines;

    /**
     * @ORM\OneToOne(targetEntity=Stock::class, mappedBy="medicament", cascade={"persist", "remove"})
     */
    private $the_stock;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
        $this->transactionLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatePeremp(): ?\DateTimeInterface
    {
        return $this->date_peremp;
    }

    public function setDatePeremp(\DateTimeInterface $date_peremp): self
    {
        $this->date_peremp = $date_peremp;

        return $this;
    }

    public function getCible(): ?string
    {
        return $this->cible;
    }

    public function setCible(string $cible): self
    {
        $this->cible = $cible;

        return $this;
    }
    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getModeConso(): ?string
    {
        return $this->mode_conso;
    }

    public function setModeConso(string $mode_conso): self
    {
        $this->mode_conso = $mode_conso;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getEffetSecondaire(): ?string
    {
        return $this->effet_secondaire;
    }

    public function setEffetSecondaire(?string $effet_secondaire): self
    {
        $this->effet_secondaire = $effet_secondaire;

        return $this;
    }

    public function getPriceUnitCarton(): ?string
    {
        return $this->price_unit_carton;
    }

    public function setPriceUnitCarton(string $price_unit_carton): self
    {
        $this->price_unit_carton = $price_unit_carton;

        return $this;
    }

    public function getPriceUnitBoite(): ?string
    {
        return $this->price_unit_boite;
    }

    public function setPriceUnitBoite(string $price_unit_boite): self
    {
        $this->price_unit_boite= $price_unit_boite;

        return $this;
    }

    public function getPriceUnitPlaquette(): ?string
    {
        return $this->price_unit_plaquette;
    }

    public function setPriceUnitPlaquette(string $price_unit_plaquette): self
    {
        $this->price_unit_plaquette = $price_unit_plaquette;

        return $this;
    }

    /**
     * @return Collection<int, Transaction>
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->addIdMedicament($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->removeElement($transaction)) {
            $transaction->removeIdMedicament($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, TransactionLine>
     */
    public function getTransactionLines(): Collection
    {
        return $this->transactionLines;
    }

    public function addTransactionLine(TransactionLine $transactionLine): self
    {
        if (!$this->transactionLines->contains($transactionLine)) {
            $this->transactionLines[] = $transactionLine;
            $transactionLine->setIdMedicament($this);
        }

        return $this;
    }

    public function removeTransactionLine(TransactionLine $transactionLine): self
    {
        if ($this->transactionLines->removeElement($transactionLine)) {
            // set the owning side to null (unless already changed)
            if ($transactionLine->getIdMedicament() === $this) {
                $transactionLine->setIdMedicament(null);
            }
        }

        return $this;
    }

    public function getTheStock(): ?Stock
    {
        return $this->the_stock;
    }

    public function setTheStock(?Stock $the_stock): self
    {
        // unset the owning side of the relation if necessary
        if ($the_stock === null && $this->the_stock !== null) {
            $this->the_stock->setMedicament(null);
        }

        // set the owning side of the relation if necessary
        if ($the_stock !== null && $the_stock->getMedicament() !== $this) {
            $the_stock->setMedicament($this);
        }

        $this->the_stock = $the_stock;

        return $this;
    }
}

src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Repository\TransactionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransactionRepository::class)
 */
class Transaction
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Contact::class, inversedBy="transactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_contact;

    /**
     * @ORM\ManyToMany(targetEntity=Medicament::class, inversedBy="transactions")
     */
    private $id_medicament;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_transaction;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

     /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $num_facture;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price_total;
    
        /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $total_paid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status_payment;

       /**
     * @ORM\Column(type="string", length=255)
     */
    private $mode_payment;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $note;

    /**
     * @ORM\OneToMany(targetEntity=TransactionLine::class, mappedBy="id_transaction")
     */
    private $transactionLines;

    public function __construct()
    {
        $this->id_medicament = new ArrayCollection();
        $this->transactionLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumFacture(): ?string
    {
        return $this->num_facture;
    }

    public function setNumFacture(string $num_facture): self
    {
        $this->num_facture = $num_facture;

        return $this;
    }

    public function getIdContact(): ?Contact
    {
        return $this->id_contact;
    }

    public function setIdContact(?Contact $id_contact): self
    {
        $this->id_contact = $id_contact;

        return $this;
    }

    /**
     * @return Collection<int, Medicament>
     */
    public function getIdMedicament(): Collection
    {
        return $this->id_medicament;
    }

    public function addIdMedicament(Medicament $idMedicament): self
    {
        if (!$this->id_medicament->contains($idMedicament)) {
            $this->id_medicament[] = $idMedicament;
        }

        return $this;
    }

    public function removeIdMedicament(Medicament $idMedicament): self
    {
        $this->id_medicament->removeElement($idMedicament);

        return $this;
    }

    public function getDateTransaction(): ?\DateTimeInterface
    {
        return $this->date_transaction;
    }

    public function setDateTransaction(\DateTimeInterface $date_transaction): self
    {
        $this->date_transaction = $date_transaction;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPriceTotal(): ?string
    {
        return $this->price_total;
    }

    public function setPriceTotal(string $price_total): self
    {
        $this->price_total = $price_total;

        return $this;
    }

    public function getTotalPaid(): ?string
    {
        return $this->total_paid;
    }

    public function setTotalPaid(string $total_paid): self
    {
        $this->total_paid = $total_paid;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStatusPayment(): ?string
    {
        return $this->status_payment;
    }



    public function setStatusPayment(string $status_payment): self
    {
        $this->status_payment = $status_payment;

        return $this;
    }

    public function getModePayment(): ?string
    {
        return $this->mode_payment;
    }

    public function setModePayment(string $mode_payment): self
    {
        $this->mode_payment = $mode_payment;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection<int, TransactionLine>
     */
    public function getTransactionLines(): Collection
    {
        return $this->transactionLines;
    }

    public function addTransactionLine(TransactionLine $transactionLine): self
    {
        if (!$this->transactionLines->contains($transactionLine)) {
            $this->transactionLines[] = $transactionLine;
            $transactionLine->setIdTransaction($this);
        }

        return $this;
    }

    public function removeTransactionLine(TransactionLine $transactionLine): self
    {
        if ($this->transactionLines->removeElement($transactionLine)) {
            // set the owning side to null (unless already changed)
            if ($transactionLine->getIdTransaction() === $this) {
                $transactionLine->setIdTransaction(null);
            }
        }

        return $this;
    }
}

templates/purchasse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}edit purchasse{% endblock %}

{% block body %}
<div class="col-md-12">

<H1>
Edit purchasse
</H1>
 <form  class="form-control"  id="transaction_edit" method="POST" action="{{path('app_purchasse_udpate', {'id': purchasse.id} )}}"> 

<div class="row">
 <div class="form-group col-md-3">
  <label  class="label"> Fournisseur</label><br>
 <select name="contact" required class="form-control">
  {# <option >please select</option> #}
{%for contact in contacts %}
  <option value="{{contact.id}}" {% if (contact.id == purchasse.idContact.id  ) %}selected='selected'{% endif %}>{{contact.name}}</option>
  {%endfor%}
</select> 
</div>

 <div class="form-group col-md-3">
 <label  class="label"> Status</label><br>
 <select  name="status" required class="form-control" id="status">
 <option >please select</option>
{%for status in statuses %}
  <option value="{{status}}"  {% if (status == purchasse.status  ) %}selected='selected'{% endif %}>{{status}}</option>
  {%endfor%}
</select> 
</div>

 <div class="form-group col-md-3">
 <label  class="label"> Status payment</label><br>
 <select name="status_payment" class="form-control" id="status_payment">
{%for status_payment in status_payments %}
  <option class="status_payment" value="{{status_payment}}" disabled {% if (status_payment == purchasse.statusPayment  ) %}selected='selected'{% endif %} >{{status_payment}}</option>
  {%endfor%}
</select> 
</div>
{# <div class="form-group">
    <input type="date" name="date_transaction" class="form-control" id="date_transaction">
</div> #}
<div class="form-group col-md-3">
 <label for="date_transaction">date transaction:</label>
    <input type="text" class="js-datetimePicker"name="date_transaction" value="{{purchasse.dateTransaction|date('Y-m-d') }}" id="date_transaction" class="form-control" />
</div>
</div>



    <input type="hidden" name="type" id="type" placeholder="type" value="purchasse" />
    {# <div class="form-group">
    <input type="text" name="total_amount" id="total_amount" class="form-control" placeholder="total_amount" />
 </div> #}

<br>


<div class="row">
		<div class=" d-flex  justify-content-center">
			<div class="col-sm-5 ">
				<div class="form-group">
					<div class="input-group">
					<span class="input-group-addon">
						<i class="fa-solid fa-tablets  fa-2xl fa-fw"></i>
					</span>
            <input type="text" name="search_medicament" id="search_medicament" class="form-control" placeholder="medicament" />
						
                    	<span class="input-group-addon">
						<i class="fa-solid fa-tablets  fa-2xl fa-fw"></i>
					</span>
					</div>
				</div>
			</div>
			</div>
			<div class="row col-sm-12 stpl_parcel_div" style="min-height: 0">
				<input type="hidden" name="edit_dropshipping_lines" id="edit_dropshipping_lines" value="1">
				<input type="hidden" id="product_row_index" value="0">
				<input type="hidden" id="count" value="{{count}}">
				<input type="hidden" id="total_amount" name="final_total" value="0">
				<div class="table-responsive">
					<table class="table table-condensed table-bordered table-striped table-responsive" id="stpl_table">
						<thead>
						<tr>
							<th class="text-center" style="width: 200px;">product</th>
							<th class="text-center" style="width: 200px;">qty</th>
							<th class="text-center" style="width: 150px;">unit_price</th>
							{# <th class="text-center" style="width: 150px;">caracteristique</th> #}
							<th class="text-center" style="width: 200px;">total</th>
							<th class="text-center"><i class="fas fa-times" aria-hidden="true"></i></th>
						</tr>
						</thead>
						<tbody>
                      {% set i = 0 %}
                        {%for transaction_line in transaction_lines %}
                       
                            <tr class="product_row">
                                <td class="text-center">
                                    {{transaction_line.idMedicament.name}}
                                    {# {{product['sku']}} #}
                                </td>
                                
                                <input type="hidden" class="product_id" value="{{transaction_line.idMedicament.id}}" name="product[{{i}}][product_id]"/>

                                <td class="text-center">
                                                <div class="input-group input-number">
                                                <b  style="width:70px;">carton:</b>
                                                    {# <span class="input-group-btn"><button type="button" class="btn btn-default btn-flat sh-quantity-down"><i class="fa fa-minus text-danger"></i></button></span> #}
                                                    <input type="number" data-min="0" value="{{transaction_line.qtyCarton}}" class="form-control input_number spl_qty_carton"  style="text-align: center;"
                                                        name="product[{{i}}][qty_carton]" min="0" value="0"> 
                                                    {# <input type="text" data-min="0" class="form-control input_number spl_qty_boite"  style="text-align: center;"
                                                        name="product[{{row_index}}][qty_boite]" value="0">  <br>
                                                    <input type="text" data-min="0" class="form-control input_number spl_qty_plaquette"  style="text-align: center;"
                                                        name="product[{{row_index}}][qty_plaquette]" value="1">  <br> #}
                                                    {# <span class="input-group-btn"><button type="button" class="btn btn-default btn-flat sh-quantity-up"><i class="fa fa-plus text-success"></i></button></span> #}
                                                </div> 
                                                        <div class="input-group input-number">
                                                        <b style="width:70px;">boite:</b>
                                                    {# <span class="input-group-btn"><button type="button" class="btn btn-default btn-flat sh-quantity-down"><i class="fa fa-minus text-danger"></i></button></span> #}
                                                <input type="number" data-min="0" value="{{transaction_line.qtyBoite}}" class="form-control input_number spl_qty_boite"  style="text-align: center;"
                                                        name="product[{{i}}][qty_boite]" min="0" value="0">
                            
                                                    {# <span class="input-group-btn"><button type="button" class="btn btn-default btn-flat sh-quantity-up"><i class="fa fa-plus text-success"></i></button></span> #}
                                                </div> 
                                                        <div class="input-group input-number">
                                                        <b style="width:70px;">plq:</b>
                                                    {# <span class="input-group-btn"><button type="button" class="btn btn-default btn-flat sh-quantity-down"><i class="fa fa-minus text-danger"></i></button></span> #}
                                                    <input type="number" data-min="0" value="{{transaction_line.qtyPlaquette}}" class="form-control input_number spl_qty_plaquette"  style="text-align: center;"
                                                        name="product[{{i}}][qty_plaquette]" min="0" value="1"> 
                            
                                                    {# <span class="input-group-btn"><button type="button" class="btn btn-default btn-flat sh-quantity-up"><i class="fa fa-plus text-success"></i></button></span> #}
                                                </div>
                                                
                                                <input type="hidden" class="spl_available_qty_carton" >
                                                <input type="hidden" class="spl_available_qty_boite" >
                                                <input type="hidden" class="spl_available_qty_plaquette" >
                                            </td>
                                <td class="text-center">
                                    <input type="text" readonly name="product[{{i}}][price_carton]" value="{{transaction_line.idMedicament.priceUnitCarton}}" class="form-control product_price_carton" style="text-align: center;" >
                                    <input type="text" readonly name="product[{{i}}][price_boite]" value="{{transaction_line.idMedicament.priceUnitBoite}}" class="form-control product_price_boite" style="text-align: center;" >
                                    <input type="text" readonly name="product[{{i}}][price_plaquette]" value="{{transaction_line.idMedicament.priceUnitPlaquette}}" class="form-control product_price_plaquette" style="text-align: center;">
                                </td>
                                {# <td class="text-center">
                                
                                        <input type="text" name="product[{{row_index}}][caracteristique]" class="form-control">
                                    
                                </td> #}
                                <td class="text-center">
                                    <input type="text" readonly name="product[{{i}}][product_price_total]" class="form-control product_price_total" style="text-align: right;" >
                                </td>
                                <td class="text-center"><i class="fa fa-times text-danger spl_remove_row cursor-pointer" aria-hidden="true"></i></td> 

                            </tr>
                            {% set i = i + 1 %}
                        {% endfor %}
						</tbody>
						<tfoot>
							
						<tr class="text-center">
							<td colspan="4"></td>
							<td><div class="pull-right"><b>Total amount:</b> <span id="total_amount_transaction">0.00Ar</span></div>
							</td>
						</tr>
						</tfoot>
					</table>
				</div>

			</div>

		
		</div>

		  <div class="form-group ">
 <label for="note">Note:</label>
    <textarea name="note" value="{{purchasse.note}}" id="note" class="form-control" /></textarea>
</div>

<br>
<div  id="add_payment">
<H2>
Payment
</H2>
{# <div class="row"> #}
 <div class="form-group col-md-4">
  <label  class="label">Mode payment</label><br>
 <select name="mode_payment" class="form-control" id="mode_payment">
{%for mode_payment in mode_payments %}
  <option value="{{mode_payment}}" {% if (mode_payment == 'cache'  ) %}selected='selected'{% endif %} {% if (mode_payment != 'cache'  ) %}disabled{% endif %} >{{mode_payment}}</option>
  {%endfor%}
</select> 
</div>

<div class="form-group col-md-4">
 <label for="payment">payé:</label>

    <input type="number" name="payment" value="{{purchasse.totalPaid}}" id="payment" class="form-control" />

</div>


</div>

   <br>

 <div class="d-flex  justify-content-end">
   <button type="submit" id="submit_transaction_edit" class="btn btn-success pull-right">Update</button>
   </div>
    </form>  
    </div> 

    {% endblock %}

templates/purchasse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All purchasses{% endblock %}

{% block body %}
<style>
 {# body {
     background-color:red;
 } #}
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
 
</style>


<div class="example-wrapper">

<div class="d-flex">
<div class="col-sm-6">
    <h1>All purchasses</h1>
    </div>
<div class="col-sm-6 "> 
        
      <a href="{{path('app_purchasse_create')}}"  class="btn btn-primary float-end"><i class="fa fa-plus" aria-hidden="true"></i>Add</a>
      
      </div>
    </div>
</div>
 <div class="row">
<div class="col-md-12">
<input class="form-control float-end" id='search_purchasse' value="{{term}}" type="search" placeholder="Search" aria-label="Search" style="width:150px;">

</div>
</div>
   
<div class="table"> 
<table class="table table-bordered">
<thead>
<tr>
<th  class="text-center">Facture N°</th>
<th class="text-center" style="width:100px;">Date</th>
<th class="text-center">Fournisseur</th>
<th class="text-center">Medicament</th>
<th class="text-center">Price</th>
<th class="text-center">payé</th>
<th class="text-center">Status payment</th>
<th class="text-center">Mode payment</th>
<th class="text-center">Action</th>

</tr>
</thead>
{% if purchasses|length > 0 %}
 {%for purchasse in purchasses %}
 {# {{dd(purchasse)}} #}
<tbody>
<tr>
<td class="text-center">{{purchasse.numFacture ?? purchasse.id}}</td>
<td class="text-center">{{purchasse.dateTransaction |date('d-m-Y')  }}</td>
<td class="text-center">{{purchasse.idContact.name }}</td>


<td class="text-center">
 {%for med in purchasse.transactionLines %}
 {# {%for medicament in med.idMedicament %}
{{medicament.name ?? "pas de medicament"  }}
<br>

{%endfor%} #}
{{med.idMedicament.name ?? "pas de medicament"  }}
<br>
{%endfor%}
</td>

<td class="text-center">{{purchasse.priceTotal }}Ar</td>
<td class="text-center">{{purchasse.totalPaid }}Ar</td>
<td class="text-center">{{purchasse.statusPayment }}</td>
<td class="text-center">{{purchasse.modePayment }}</td>
<td>
<div class="btn-group" role="group">
<button type="button" id="btnGroupDrop1"  class="btn btn-primary dropdown-toggle" aria-haspopup="true" aria-expanded="false" data-bs-toggle="dropdown">Action <span class="caret"></span></button>
<div class="dropdown-menu" >
<button type="button" href="" data-bs-toggle="modal" data-href="{{path('app_purchasse_show', {id: purchasse.id})}}"  data-bs-target="#create_modal"  class="dropdown-item my_modal" ><i class="fas fa-eye" aria-hidden="true"></i> view</button>
<a href="{{path('app_purchasse_edit', {id: purchasse.id})}}"  class="dropdown-item" ><i class="fas fa-edit" aria-hidden="true"></i>edit</a>

<a href="{{path('app_purchasse_delete', {id: purchasse.id})}}"  class="dropdown-item"><i class="fas fa-trash" aria-hidden="true"></i>delete</a>
</div>
</div>
</td>
</tr>
</tbody>


 {%endfor%}

 {% else %}
<tbody>
<tr>
<td colspan="9">
 <H4 class="text-center">vide</H4>
 </td>
 </tr>
 </tbody>
 {% endif %}
</table>
</div>
 

           <div class="modal fade modal" id="create_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
         
       </div>  
       </div>
{% endblock %}
{% block javascripts %}
<script type="text/javascript">
       
</script>
{% endblock %}

templates/purchasse/show.html.twig
{#<div class="modal fade" id="show" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">#}
        <div class="modal-content">
        <div class="container-fluid">
        <div class="row">
            <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">purchasse</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

            </div>
            <div class="modal-body">
 

<div class="row">
<div class="col-md-4">
<b>facture No:</b>
{{purchasse.numFacture ?? purchasse.id}}
<br>
<b>Fournisseur:</b><br>
{{purchasse.idContact.name}}
<br>
{{purchasse.idContact.contact}}
</div>
<div class="col-md-4">
</div>
<div class="col-md-4">
<b>Date:</b>
{{purchasse.dateTransaction |date('d-m-Y')  }}
<br>
<b>Status:</b>
{{purchasse.status  }}
<br>
<b>Status payment:</b>
{{purchasse.statusPayment  }}
<br>
<b>Mode payment:</b>
{{purchasse.modePayment  }}
</div>
</div>
   <br>
<div class="table-responsive"> 
<table class="table table-bordered">
<thead>
<tr>
{# <th>#</th> #}
<th class="text-center">Medicament</th>
<th class="text-center">Price carton</th>
<th class="text-center">Price boite</th>
<th class="text-center">price plaquette</th>
<th class="text-center">Qty carton</th>
<th class="text-center">Qty boite</th>
<th class="text-center">Qty plaquette</th>

<th class="text-center">price</th>
</tr>
</thead>
 
 {# {{dd(purchasse)}} #}
<tbody>
{%for med in purchasse.transactionLines %}
<tr>
{# <td>{{purchasse.id}}</td> #}

<td class="text-center">{{med.idMedicament.name ?? "pas de nom" }}</td>
<td class="text-center">{{med.idMedicament.priceUnitCarton  }} Ar</td>
<td class="text-center">{{med.idMedicament.priceUnitBoite  }} Ar</td>
<td class="text-center">{{med.idMedicament.priceUnitPlaquette  }} Ar</td>
<td class="text-center">{{med.qtyCarton  }}</td>
<td class="text-center">{{med.qtyBoite }}</td>
<td class="text-center">{{med.qtyPlaquette  }}</td>
<td class="text-center">{{med.price  }} Ar</td>


</tbody>

</tr>
 {%endfor%}
</table>
</div>
<br>
<div class="payment">
PAYMENT



 <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="table-responsive">
          <table class="table bg-gray">
            <tr>
              <th>Total: </th>
              <td></td>
              <td><span class="display_currency pull-right" data-currency_symbol="true">{{ purchasse.priceTotal }} Ar</span></td>
            </tr>
            <tr>
              <th>Total paid:</th>
              <td><b>(-)</b></td>
              <td><div class="pull-right"><span class="display_currency">{{ purchasse.totalPaid }} Ar</span> </span></div></td>
            </tr>
           
            {# <tr>
              <th>{{ __('sale.order_tax') }}:</th>
              <td><b>(+)</b></td>
              <td class="text-right">
      
                    <strong><small>{{$k}}</small></strong> - <span class="display_currency pull-right" data-currency_symbol="true">{{ $v }}</span><br>
                 
              </td>
            </tr> #}
          
            <tr>
              <th>due:</th>
              <td></td>
              <td>
                <!-- Converting total paid to string for floating point substraction issue -->
   {%if  purchasse.totalPaid >= purchasse.priceTotal %}
                <span class="display_currency pull-right" data-currency_symbol="true" >{{ 0 }} Ar</span></td>
      {%else %}     
                <span class="display_currency pull-right" data-currency_symbol="true" >{{ purchasse.priceTotal - purchasse.totalPaid }} Ar</span></td>
      {%endif %}         
            </tr>
          </table>
        </div>
      </div>
</div>

 </div>
   <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
 </div>
 </div>
        </div><!-- /.modal-content -->
 {#   </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
#}